# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/bolt-sidecar"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    groups:
      sidecar-breaking:
        patterns:
          - "*"
        update-types:
          - "major"
      sidecar-non-breaking:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/bolt-cli"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    groups:
      cli-breaking:
        patterns:
          - "*"
        update-types:
          - "major"
      cli-non-breaking:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/bolt-boost"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    groups:
      boost-breaking:
        patterns:
          - "*"
        update-types:
          - "major"
      boost-non-breaking:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
