postgres:
  hostname: db
  port: 5432
  db_name: helixdb
  user: postgres
  password: postgres
  region: 1
  region_name: "eu-central"

redis:
  url: redis://redis:6379

simulator:
  url: http://builder:8545

beacon_clients:
  - url: http://beacon:4000

builders:
  - pub_key: "aa1488eae4b06a1fff840a2b6db167afc520758dc2c8af0dfb57037954df3431b747e2f900fe8805f05d635e9a29717b"
    builder_info:
      collateral: "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
      is_optimistic: false
      builder_id: "Bolt Builder"

# If empty, all routes are enabled
router_config:
  enabled_routes: []

network_config: !Holesky

website:
  enabled: true
  port: 8080
  listen_address: "0.0.0.0"
  show_config_details: false
  network_name: "holesky"
  relay_url: https://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@relay-holesky.bolt.chainbound.io
  relay_pubkey: 0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5
  link_beaconchain: https://holesky.beaconcha.in
  link_etherscan: https://holesky.etherscan.io
  link_data_api: https://relay-holesky.bolt.chainbound.io
